### PR TITLE
starting assignment-2

### PR DESCRIPTION
**Pull request by ammarahmed93**
Started working on part 1 of assignment 2. I already built the Decision Trees (DT) and Random Forests (RF) models and currently working on building the Neural Networks (NN) - part3 of question 1.

### CODE REVIEW

**Comment by ammarahmed93** [comment]
I have the mlpClassifier for the NN working but we still need to tune up the parameters for all the classifiers and justify. 
"example: depth of tree, size of neural network, ensembles for RF) you have chosen and justify. Briefly describe the algorithms employed by the libraries you are using (example ID3, C4.5, C5.0 and CART for DT)."

**Comment by ammarahmed93** [comment]
* Tuned the parameters: max_depth_tree and min_samples_leaf for the decision tree classifier. The AUC curve will be used to justify and explain as of why we chose the values. 
* Still need to tune the parameters for the random forests and the neural networks (pending)

**Comment by ammarahmed93** [comment]
Decision tree, Random Forest, and Neural Network classifiers are tuned. This completes the coding part of part3 of question 1.  The explanation and justification regarding to choosing the parameters will go in the report.

**Comment by adkulas** [comment]
Thanks so much for starting this Ammar, hopefully I'll have some time to dive in and help you

**Pull request merged**
